# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: installing markdown-to-html
    init: cd docs/ # runs during prebuild
  - name: install dependencies
    command: npm install -g markdown-to-html
  - name: compile markdown to html
    command: markdown test.md > test.html

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5500
    onOpen: open-preview
