modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/lumien231/Random-Things"
[[mods]] #mandatory
modId="randomthings" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Random Things" #mandatory
logoFile="randomthings.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="lumien231 and Slick" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Random Things packed into one Mod.
'''