name: tagged-release

on:
  push:
    tags:
      - v*

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest

    steps:
      - name: Build jar
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 2
          command: ./gradlew build

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            LICENSE
            CHANGELOG.md
            ./build/libs/*.jar