name: create-tagged-release

on:
  push:
    tags:
      - v*.*.*

jobs:
  pre-release:
    name: Create Tagged Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Update Gradle Permissions
      run: chmod +x gradlew

    - name: Build Jar
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 2
        command: ./gradlew cleanJar build

    - name: Create Release and Upload
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: |
          LICENSE
          CHANGELOG.md
          ./build/libs/*.jar
