name: Random Things Documentation Deployment

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile docs/ folder
        run: echo Hello from Github Actions
